### ISSUE TITLE
Building Fosstars Action Docker Image Failed: Maven `3.6.3` Not Found (`404`)

### ISSUE THREAD

**Issue by Johannes-Schneider** [SAP/fosstars-rating-core-action#28]
Dear team,

we are using your action in [our repository](https://github.com/SAP/btp-environment-variable-access/blob/main/.github/workflows/fosstars-project-report.yml).
Since last week Friday (09.06.) the action has been failing.
When inspecting the log output a bit closer, I found following error message:

```
  Step 3/9 : RUN wget https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz &&     HASH=c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0 &&     echo "$HASH apache-maven-3.6.3-bin.tar.gz" | sha512sum --check --status &&     tar xf apache-maven-3.6.3-bin.tar.gz -C /opt
   ---> Running in 301113457c9e
  --2023-06-12 07:34:21--  https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
  Resolving downloads.apache.org (downloads.apache.org)... 88.99.95.219, 135.181.214.104, 2a01:4f8:10a:201a::2, ...
  Connecting to downloads.apache.org (downloads.apache.org)|88.99.95.219|:443... connected.
  HTTP request sent, awaiting response... 404 Not Found
  2023-06-12 07:34:21 ERROR 404: Not Found.
```
(This run was triggered just a few minutes ago after updating the action to the latest available version, which is `1.11.0` at this point in time)

Apparently, your Docker image relies on an older version of Maven (`3.6.3`, [here](https://github.com/SAP/fosstars-rating-core-action/blob/main/Dockerfile#L7-L10)), which doesn't seem to be available online any longer.

Can you please check and update the Maven you are using within your Docker image?

Best regards,
Johannes

**Comment by sourabhsparkala** [comment]
@Johannes-Schneider updated with [1.12.0](https://github.com/SAP/fosstars-rating-core-action/releases/tag/v1.12.0)

**Comment by Johannes-Schneider** [comment]
Hi @sourabhsparkala,

thanks for the quick update. Unfortunately, it seems you forgot to also update the SHA512 checksum of the tar archive.
Now the action is failing with following message:

```
  2023-06-12 11:13:41 (9.80 MB/s) - ‘apache-maven-3.9.2-bin.tar.gz’ saved [9248920/9248920]
  
  The command '/bin/sh -c wget https://downloads.apache.org/maven/maven-3/3.9.2/binaries/apache-maven-3.9.2-bin.tar.gz &&     HASH=f7296534ce624f688268e55544ffdf0b37562ac71dbcede4fe4f994b4e9487b7d66934849204373e127cfacc709cd5fd9152a53c06d778fc391aee84aa3364a3 &&     echo "$HASH apache-maven-3.9.2-bin.tar.gz" | sha512sum --check --status &&     tar xf apache-maven-3.9.2-bin.tar.gz -C /opt' returned a non-zero code: 1
```

When checking [the hash of the archive](https://downloads.apache.org/maven/maven-3/3.9.2/binaries/apache-maven-3.9.2-bin.tar.gz.sha512) you can quickly see that the value expected by your script and the one coming from the download page don't match up.

Best regards,
Johannes

**Comment by sourabhsparkala** [comment]
Hi @Johannes-Schneider, yes I have fixed it. Will release shortly

**Comment by sourabhsparkala** [comment]
Fixed with https://github.com/SAP/fosstars-rating-core-action/releases/tag/v1.12.1
