### ISSUE TITLE
`404` Maven `3.9.2` not found when building the action's docker image

### ISSUE THREAD

**Issue by Johannes-Schneider** [SAP/fosstars-rating-core-action#31]
Hi colleagues,

this is basically the same issue as I reported two weeks ago (#28).
It seems like the latest (and only available Maven version) is now `3.9.3` (I checked by following this link: https://downloads.apache.org/maven/maven-3/).

I suggest you find a more stable approach for getting the latest / a specific maven version, as the current approach seems to be too flaky.

Best regards,
Johannes

**Comment by sourabhsparkala** [comment]
You are right, I was also not happy with the solution provided. Let me work on a proper reliable fix.

**Comment by Johannes-Schneider** [comment]
Hey @sourabhsparkala 

any progress on this issue?
